### ISSUE TITLE
Better error handling on "No space left on device" situations

### ISSUE THREAD

**Issue by godlike64** [upgrades-migrations/redhat-upgrade-tool#17]
Hi,

I was just attempting a run of the redhat-upgrade-tool on a local system, only to have it fail with an IOError:

~~~
Continue with the upgrade [Y/N]? y
getting boot images...
initramfs-redhat-upgrade-tool.img                                                                                                                                                                                     |  48 MB     00:00 ... 
Traceback (most recent call last):
  File "/usr/bin/redhat-upgrade-tool", line 431, in <module>
    main(args)
  File "/usr/bin/redhat-upgrade-tool", line 298, in main
    kernel, initrd = f.download_boot_images() # TODO: force arch?
  File "/usr/lib/python2.6/site-packages/redhat_upgrade_tool/download.py", line 449, in download_boot_images
    copy2(initrd, initrdpath)
  File "/usr/lib64/python2.6/shutil.py", line 95, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.6/shutil.py", line 52, in copyfile
    copyfileobj(fsrc, fdst)
  File "/usr/lib64/python2.6/shutil.py", line 31, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device
~~~

However, I did not know to where it was attempting to copy this, so I had to add a couple of print statements in order to find out it was on /boot. After deleting old kernel/initramfs versions I was able to successfully continue. However, I believe it would be best if:

- Either the preupg tool notifies this
- The redhat-upgrade-tool graciously handles this exception

**Comment by bocekm** [comment]
Fixed by PR https://github.com/upgrades-migrations/redhat-upgrade-tool/pull/19.
